/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.admin;


import business.Product;
import business.ProductCatalog;
import business.Validator;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Neha Ghate
 */
public class AddProductsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDrugsJPanel
     */
    private JPanel userProcessContainer;
    private ProductCatalog productCatalog;
    private Validator validator;
    public AddProductsJPanel(JPanel userProcessContainer, ProductCatalog productCatalog) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.productCatalog = productCatalog;
    }
    
    private void backAction() {
        
        //add refresh button and also call populateTable
    userProcessContainer.remove(this);
    Component[] componentArray = userProcessContainer.getComponents();
    Component component = componentArray[componentArray.length - 1 ];
    ViewSupplierCompany viewpharmaPanel = (ViewSupplierCompany) component;
    viewpharmaPanel.populateTable();
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.previous(userProcessContainer);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        drugIDJTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        drugAvailibilityJTextField = new javax.swing.JTextField();
        createProductJButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        errQtyjLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        productNamejTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        floorPricejTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ceilingPricejTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        targetPricejTextField3 = new javax.swing.JTextField();

        jLabel1.setText("Add Product Details");

        jLabel2.setText("Product ID");

        drugIDJTextField.setEnabled(false);

        jLabel8.setText("Quantity");

        drugAvailibilityJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drugAvailibilityJTextFieldActionPerformed(evt);
            }
        });

        createProductJButton.setText("Create Product");
        createProductJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProductJButtonActionPerformed(evt);
            }
        });

        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        errQtyjLabel7.setForeground(new java.awt.Color(255, 0, 0));

        jLabel12.setText("Product Name");

        jLabel3.setText("Floor Price");

        jLabel4.setText("Ceiling Price");

        jLabel5.setText("Target Price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(createProductJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(3, 3, 3))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel12)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(floorPricejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ceilingPricejTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(targetPricejTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(drugIDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(167, 167, 167)
                                        .addComponent(jLabel8))
                                    .addComponent(productNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(errQtyjLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(drugAvailibilityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel1)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(drugIDJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(errQtyjLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(productNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(drugAvailibilityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(floorPricejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ceilingPricejTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(targetPricejTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createProductJButton)
                    .addComponent(jButton1))
                .addGap(159, 159, 159))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createProductJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProductJButtonActionPerformed
        // TODO add your handling code here:
        String productName = productNamejTextField.getText();
        validator = new Validator();
        
        Product product =  new Product();
        
        ArrayList<String> errorArray = new ArrayList();
        
        if(validator.isStringValid(productName)){
            product.setProductName(productName);
        }
        else
        {
           errorArray.add("Product Name");
           // errDrugNamejLabel.setText("Drug name cannot be empty");
           
        }
        
         if((validator.isStringValid(floorPricejTextField1.getText())) &&
                (validator.isValidFloat(floorPricejTextField1.getText())) ){

            float floorPrice = Float.parseFloat(floorPricejTextField1.getText());
            product.setFloorPrice(floorPrice);
           errQtyjLabel7.setText("");
        }
        else
        {
            errorArray.add("Floor Price ");
            //errQtyjLabel7.setText("Enter a valid availability");
        }
         
         
          if((validator.isStringValid(targetPricejTextField3.getText())) &&
                (validator.isValidFloat(targetPricejTextField3.getText())) ){

             float targetPrice = Float.parseFloat(targetPricejTextField3.getText());
            product.setTargetPrice(targetPrice);
           errQtyjLabel7.setText("");
        }
        else
        {
            errorArray.add("Target Price ");
            //errQtyjLabel7.setText("Enter a valid availability");
        }
          
          
           if((validator.isStringValid(ceilingPricejTextField2.getText())) &&
                (validator.isValidFloat(ceilingPricejTextField2.getText())) ){

            float ceilingPrice = Float.parseFloat(ceilingPricejTextField2.getText());
            product.setFloorPrice(ceilingPrice);
           errQtyjLabel7.setText("");
        }
        else
        {
            errorArray.add("Ceiling Price ");
            //errQtyjLabel7.setText("Enter a valid availability");
        }
         
        
        if((validator.isStringValid(drugAvailibilityJTextField.getText())) &&
                (validator.isValidInteger(drugAvailibilityJTextField.getText())) ){
            int Availibility = Integer.parseInt(drugAvailibilityJTextField.getText());
           product.setAvailibility(Availibility);
           errQtyjLabel7.setText("");
        }
        else
        {
            errorArray.add("Quantity ");
            //errQtyjLabel7.setText("Enter a valid availability");
        }
        
                
        //Check is done if the errorArray contains error messages
        if(!errorArray.isEmpty()){
        
        String message = "";
        //Iterate the errorListArray with foreach
        for( String error : errorArray )
            {
                message += error + " \n";
            }
            JOptionPane.showMessageDialog(null,message +"are empty fields. Please enter the values.","Error ",JOptionPane.ERROR_MESSAGE);   
        }
        else{
            productCatalog.addProduct(product);
        JOptionPane.showMessageDialog(null, "Product is added","Store Addition",JOptionPane.INFORMATION_MESSAGE);       
        
        }
        
    }//GEN-LAST:event_createProductJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                backAction();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void drugAvailibilityJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drugAvailibilityJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drugAvailibilityJTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ceilingPricejTextField2;
    private javax.swing.JButton createProductJButton;
    private javax.swing.JTextField drugAvailibilityJTextField;
    private javax.swing.JTextField drugIDJTextField;
    private javax.swing.JLabel errQtyjLabel7;
    private javax.swing.JTextField floorPricejTextField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField productNamejTextField;
    private javax.swing.JTextField targetPricejTextField3;
    // End of variables declaration//GEN-END:variables

    
}
